### ISSUE TITLE
Job objectives stay when switching job.

### ISSUE THREAD

**Issue by Revanizer** [SanAndreasNoLimits/SANLRPG#10]
For example, when you are trucker and switch to pilot, the pilot can still do the trucker objectives.

**Comment by 1B0Y** [comment]
Can we get a list of jobs that are affected by this? (don't say "all of them" either...)

**Comment by 1B0Y** [comment]
Looked into the system, and noticed that it triggers events based on the job, for example: onPlayerGetJobPilot. Looking more into the system, there are no events for when a player resigns. The job system itself will need some more work done, following some of the jobs that also need to listen for these events to clear itself.

Work to be done:
 - Rewrite the events in the system to return the job name with "onPlayerGetJob" rather than combining it to the event string. This was most likely implemented like this due to old MTA style coding.
 - Create an event in resign so jobs can do the appropriate tasks to clear up.
 - Check each job to make sure it's listening to the new event that we implement, so that they can clear when the player resigns or changes jobs.

Patch should be available by tomorrow.

**Comment by 1B0Y** [comment]
Half of the jobs patched with the new chances for the job core. The remaining jobs will be patched tomorrow.

**Comment by 1B0Y** [comment]
All done.
